__author__ = "Lukas Mahler"
__version__ = "0.3.1"
__date__ = "08.04.2026"
__email__ = "m@hler.eu"
__status__ = "Development"


import struct
import zlib

from cs2inspect._util_base import MAX_HEX_PAYLOAD_SIZE
from cs2inspect.econ_pb2 import CEconItemPreviewDataBlock


def float_to_bytes(float_value: float) -> int:
    float_bytes = struct.pack('>f', float_value)
    return struct.unpack('>I', float_bytes)[0]


def bytes_to_float(int_value: int) -> float:
    int_bytes = struct.pack('>I', int_value)
    return struct.unpack('>f', int_bytes)[0]


def hex_to_bytes(hex_str: str) -> bytes:
    return bytes.fromhex(hex_str)


def to_hex(data_block: CEconItemPreviewDataBlock) -> str:
    """
    Encode a CEconItemPreviewDataBlock protobuf object into a valid inspect link hex payload string.

    :param data_block: The protobuf item data to encode.
    :type data_block: CEconItemPreviewDataBlock

    :return: The generated uppercase hex string including the null byte prefix and unmasked CRC checksum.
    :rtype: str
    """
    # Needs to be prefixed with a null byte
    buffer = bytearray([0])
    buffer.extend(data_block.SerializeToString())

    # calculate the checksum
    crc = zlib.crc32(buffer)
    xored_crc = (crc & 0xFFFF) ^ (data_block.ByteSize() * crc)

    buffer.extend((xored_crc & 0xFFFFFFFF).to_bytes(length=4, byteorder='big'))

    # Must be upper case
    return buffer.hex().upper()


def from_hex(hex_str: str) -> CEconItemPreviewDataBlock:
    """
    Decode an inspect link hex payload string into a CEconItemPreviewDataBlock protobuf object.

    :param hex_str: The hex payload extracted from an inspect link.
    :type hex_str: str

    :return: The deserialized protobuf item data block.
    :rtype: CEconItemPreviewDataBlock
    """
    # Reject absurdly large payloads (way beyond any real inspect link)
    if len(hex_str) > MAX_HEX_PAYLOAD_SIZE:
        raise ValueError(f"Hex payload too large ({len(hex_str)} chars), maximum is {MAX_HEX_PAYLOAD_SIZE}")

    # Convert hex string to bytes
    data_bytes = hex_to_bytes(hex_str)

    if not data_bytes:
        raise ValueError("Empty hex string")

    if len(data_bytes) < 5:
        raise ValueError("Hex payload too short to contain valid data and CRC")

    # If first byte is not 0, it's an XOR masked link (game-generated)
    is_masked = data_bytes[0] != 0
    if is_masked:
        mask = data_bytes[0]
        data_bytes = bytes(b ^ mask for b in data_bytes)

        if data_bytes[0] != 0:
            raise ValueError("Invalid masked inspect hex payload")

    # Split payload and CRC
    payload = data_bytes[:-4]
    stored_crc_bytes = data_bytes[-4:]

    # CRC verification (only reliable for non-masked payloads generated by this library)
    if not is_masked:
        stored_crc = int.from_bytes(stored_crc_bytes, byteorder='big')
        crc = zlib.crc32(payload)
        proto_size = len(payload) - 1  # Exclude the leading null byte
        xored_crc = (crc & 0xFFFF) ^ (proto_size * crc)

        if (xored_crc & 0xFFFFFFFF) != stored_crc:
            raise ValueError("CRC checksum mismatch")

    # Remove the first null byte
    data_bytes = payload[1:]

    # Deserialize the protobuf message
    data_block = CEconItemPreviewDataBlock()
    data_block.ParseFromString(data_bytes)

    return data_block


if __name__ == '__main__':
    exit(1)
